### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by kojix2** [unagiootoro/ruby-dnn#1]
Hello.

I recently introduced rubydnn on reddit.
The reddit comment was "improve the documentation".

I'm not an engineer or a programmer.
I don't really understand deep learning / neural networks.

But, I think the concept of ruby-dnn is nice.

Please brush up the README. This will encourage many people to use it.

I think the following list is useful.
https://github.com/matiassingers/awesome-readme

Flux.jl
https://github.com/FluxML/Flux.jl

Reddit
https://www.reddit.com/r/ruby/comments/bwnely/rubydnn/

**Comment by unagiootoro** [comment]
Hello.

Thank you for issue report.

I will in the README, add the example of MNIST in MLP and the list of implemented Layers and Optimizers.
Currently, I am making a version 0.10.0.
So,  When I update to version 0.10.0, add them.

**Comment by kojix2** [comment]
How about adding CI badge?

![](https://api.travis-ci.org/travis-ci/travis-web.svg?branch=master)
![](https://camo.githubusercontent.com/43002cf583488e19925686dabdf112001254723f/68747470733a2f2f636972636c6563692e636f6d2f67682f436972636c6543492d5075626c69632f636972636c6563692d64656d6f2d727562792d7261696c732e7376673f7374796c653d737667)

`.travis.yml` already exists in the repository. Is setup completed?

**Comment by unagiootoro** [comment]
I want adding CI badge.
However, I don't know travis CI well. 
(The repository on .travis.yml remains as automatically generated by the bundle gem command)

So I need to learning more about it. 
Therefore it'll take some time.

**Comment by kojix2** [comment]
Okay. It's easy to set up. Just log in and press a few buttons.

**Comment by unagiootoro** [comment]
Added CI batch.
README is still insufficient, but I will add the contents in the future.
