### ISSUE TITLE
Unclear part of the dcgan exsample

### ISSUE THREAD

**Issue by kojix2** [unagiootoro/ruby-dnn#18]
[Rubocop](https://github.com/rubocop-hq/rubocop) find out this line is unclear...

```
examples/dcgan/dcgan.rb:132:14: W: Lint/Void: Operator + used in void context.
    dis_loss + @dis.train_on_batch(images, y_fake)
```

https://github.com/unagiootoro/ruby-dnn/blob/5114f1e88c7eaa25e716590a330fe84f77c613a8/examples/dcgan/dcgan.rb#L124-L139

**Comment by unagiootoro** [comment]
Thank you for issue report.
Because this is a bug, I will fix it.
