### ISSUE TITLE
CR+LF (Windows) line break types. 

### ISSUE THREAD

**Issue by kojix2** [unagiootoro/ruby-dnn#3]
Hi.

I think ruby-dnn should use LF line breaks.
ruby-dnn uses Windows (CR LF) line breaks.

When you open a file in vim, it looks like this:

![image](https://user-images.githubusercontent.com/5798442/59814964-06ab4600-9352-11e9-99cc-75650688106b.png)

You see `^ M` at the end of every line. `^M` means (CR).

This is not a fault. 

But, Cross-platform open source project usually use LF line breaks. 
Potential contributors must set CR + LF in the editor for ruby-dnn project. 

Again, this is not a mistake. You can leave the line breaks as they are.
But that would be a disadvantage in attracting users and contributors.

**Comment by unagiootoro** [comment]
Replaced CRLF of all files with LF.

**Comment by kojix2** [comment]
Thank you!
